=== DamiFuma02/GITCODING/WEB/Materiale didattico-20211003/Laboratorio/XML/Esercizi/dizionario.dtd
<!ELEMENT dizionario (voce*)> 
<!ELEMENT voce (termine, pronuncia, significato+)>  
<!ELEMENT termine (#PCDATA)>
<!ELEMENT pronuncia (#PCDATA)> 
<!ELEMENT significato (definizione, esempio*)> 
<!ELEMENT definizione (#PCDATA)> 
<!ELEMENT esempio (#PCDATA)> 
<!ATTLIST dizionario lingua (english|french|german|italian|spanish) 'italian'>

=== DamiFuma02/GITCODING/WEB/Materiale didattico-20211003/Laboratorio/XML/Esercizi/dizionario.xml
<?xml version="1.0" ?>
<!-- <!DOCTYPE dizionario SYSTEM "dizionario.dtd">  -->
<dizionario lingua="english">
    <voce>
        <termine>mouse</termine>
        <pronuncia>maus</pronuncia>
        <significato>
            <definizione>topo</definizione>
            <esempio>mouse hole</esempio>
            <esempio>mouse color</esempio>
        </significato>
        <significato>
            <definizione>mouse</definizione>
            <esempio>...</esempio>
        </significato>
    </voce>
    <voce>
        <termine>keyboard</termine>
        <pronuncia>...</pronuncia>
        <significato>
            <definizione>...</definizione>
            <esempio> ... </esempio>
        </significato>
    </voce>
</dizionario>
