=== DamiFuma02/GITCODING/WEB/Materiale didattico-20211003/Laboratorio/XML/Esercizi/es1a.dtd
<!ELEMENT studente (nominativo+, corso+)>
<!ELEMENT nominativo (cognome+,nome+, dataNascita?)>
<!ELEMENT cognome (#PCDATA)>
<!ELEMENT nome (#PCDATA)>
<!ELEMENT dataNascita (#PCDATA)>
<!ELEMENT corso (nomeCorso+, crediti+, voto?)>
<!ELEMENT nomeCorso (#PCDATA)>
<!ELEMENT crediti EMPTY>
<!ELEMENT voto (#PCDATA)>

<!ATTLIST corso link IDREFS #REQUIRED>

<!ATTLIST corso annoAccademico (1 | 2 | 3) #REQUIRED>
<!ATTLIST corso tipoLaurea (triennale | magistrale) "triennale">
<!ATTLIST crediti numero (6 | 9 | 12) #REQUIRED>
<!ATTLIST annoFrequenza anno (1 | 2 | 3) #REQUIRED>
<!ATTLIST studente matricola ID #REQUIRED>

=== DamiFuma02/GITCODING/WEB/Materiale didattico-20211003/Laboratorio/XML/Esercizi/es1a.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/css" href="main.css"?>
<!DOCTYPE studente SYSTEM "es1a.dtd">
<studente matricola="ibml">
    <nominativo>
        <cognome>FUMAGALLI</cognome>
        <nome>DAMIANO</nome>
        <dataNascita>05/05/2002</dataNascita>
    </nominativo>
    <corso annoAccademico="2" link="ibml">
        <nomeCorso></nomeCorso>
        <crediti numero="6" />
        <voto>10</voto>
    </corso>
</studente>
