<?xml version="1.0"?>
<!DOCTYPE GIORNALE [
<!ELEMENT GIORNALE (ARTICOLO+)>
<!ELEMENT ARTICOLO (TITOLO, SOTTOTITOLO, INTESTAZIONE, CORPO, NOTE)>
<!ELEMENT TITOLO (#PCDATA)>
<!ELEMENT SOTTOTITOLO (#PCDATA)>
<!ELEMENT INTESTAZIONE (#PCDATA)>
<!ELEMENT CORPO (#PCDATA)>
<!ELEMENT NOTE (#PCDATA)>

<!ATTLIST ARTICOLO AUTORE CDATA #REQUIRED>
<!ATTLIST ARTICOLO CURATORE CDATA #IMPLIED>
<!ATTLIST ARTICOLO DATA CDATA #IMPLIED>
<!ATTLIST ARTICOLO EDIZIONE CDATA #IMPLIED>

<!ENTITY GIORNALE "Vervet Logic Times">
<!ENTITY EDITORE "Vervet Logic Press">
<!ENTITY COPYRIGHT "Copyright 1998 Vervet Logic Press">]>

<GIORNALE>
	<ARTICOLO AUTORE="IO">
		<TITOLO>I sistemi operativi</TITOLO>
		<SOTTOTITOLO>Open-source e closed-source</SOTTOTITOLO>
		<INTESTAZIONE>Una nostra indagine</INTESTAZIONE>
		<CORPO>
			bla bla bla ... 
		</CORPO>
		<NOTE>
			&GIORNALE; &EDITORE; &COPYRIGHT;
		</NOTE>
	</ARTICOLO>
</GIORNALE> 
