=== DamiFuma02/GITCODING/WEB/Materiale didattico-20211003/Laboratorio/XML/Esercizi/libro.dtd
<!ELEMENT libro       (autore+,titolo,capitolo+)>
<!ENTITY % contenuto "titolo, (paragrafo|figura)*">
<!ELEMENT capitolo    (%contenuto;,sezione*)>
<!ELEMENT sezione     (%contenuto;)>
<!ELEMENT autore      (#PCDATA)>
<!ELEMENT titolo      (#PCDATA)>
<!ELEMENT paragrafo   (#PCDATA|riferimento)*>
<!ELEMENT figura      (#PCDATA)>
<!ELEMENT riferimento EMPTY>
<!ATTLIST libro isbn ID #IMPLIED>
<!ATTLIST riferimento risorsa IDREF #REQUIRED>

=== DamiFuma02/GITCODING/WEB/Materiale didattico-20211003/Laboratorio/XML/Esercizi/libro.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE libro SYSTEM "libro.dtd">
<libro isbn="isbn:978-81-7525-766-5">
    <autore>Mario Rossi</autore>
    <titolo>La storia infinita (ben tre paragrafi)</titolo>
    <capitolo>
        <titolo>Capitolo I</titolo>
        <paragrafo>Questo è il primo paragrafo.</paragrafo>
        <paragrafo>Questo è il secondo paragrafo.</paragrafo>
        <paragrafo>Questo è il terzo e ultimo paragrafo.</paragrafo>
    </capitolo>
</libro>
